### PR TITLE
Mint.com signup page: HTML and CSS

### PR DESCRIPTION
**Pull request by jamezjaz**
This is HTML and CSS project, we;

- Added Sign In button
- Added a logo
- Added some icons
- Added input boxes
- Added Create Account button
- Added footer and Privacy Settings button

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks good :+1: 

Here are the thisng you need to fix before this project can be approved:

* [ ] Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows one error in your project.
* [ ] All stickler errors should be fixed.
* [ ] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))
* [ ] Row under intuit logo should contain Mint logo and text, Quickbooks logo an text,  Turbotax logo and text  (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
* [ ] Email `<input>` should be of type `email` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [ ] Phone `<input>` should be of type `tel` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [ ] Form should look more like original, it is a bit smaller, font looks bigger. Next part doesn't look well centered:
image
Original:
image
 
### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Lets fix the lint errors
- [ ] For the submit button ,give space between the icon and text 
.





 

### Make changes and submit another code review request.
*Happy coding*

**Comment by SofiBretz** [comment]
Code under review by SofiBretz. Thanks!✨

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] Consider fixing the errors on your Validator [Here ](https://validator.w3.org/#validate_by_upload)is the link to do a search for the errors on your project. 

Screenshot from 2020-02-28 08-02-15

- [ ] Consider to add space in the text and change the links color to 'blue', as the original page:

Screenshot from 2020-02-28 08-09-55

Original:
Screenshot from 2020-02-28 08-14-12

- [ ] It’s better to delete commented code on your CSS file.  [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) you can see the information about this.
COMMENTLINE

[OPTIONAL]

- [ ] Consider adding the demo link in your readme file.

- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by majovanilla** [comment]
Hi team!!

Everything looks great, but I found a small gray div in the bottom right part of your page. 
This one shouldn't be there. Please remove it!

Screenshot from 2020-02-28 06-58-04

You are almost done!! Keep it up!! :muscle: 

**Status: changes required.**

Find me on slack (@majo) if you need anything.

**Comment by majovanilla** [comment]
AWESOME!!!

Your project has passed all the requirements.

You are good to go.

### Project status: APPROVED :heavy_check_mark:

**Pull request merged**
